### ISSUE TITLE
How can i print a int or a str

### ISSUE THREAD

**Issue by iudf662** [official-yehan-wasura/Y-Sharp-Programming-Language#2]
How can i print a int or a str with y#

**Comment by RezSat** [comment]
Oh, just simply use print, that's all , for example: 
`print 10; `
`print "Hello, World!";`

**Comment by RezSat** [comment]
look at my examples, I will add some more examples there.

**Comment by RezSat** [comment]
but there are some problems, when using variables, you can't print int variables but you can print str variables,  :
`str  name = "Yehan Wasura";
print name;
`

The problem when trying to print INT variable is that it won't show the value in the result console and also it does not show any errors, it likely just skipping it or something, I didn't really looked deep into it and I really can't remember much of the things here, because it's being some time, but I will take look and try to fix it soon.

**Comment by RezSat** [comment]
alright buddy, I have found the problem and I have fixed it, The thing fixed was in the file Objects/builtinObjects.py, there your have code like this : 
`try: self.exec_string += ast['arguments'][0] + ")"` and I just changed it to :
`try: self.exec_string += str(ast['arguments'][0]) + ")"`. making any arguments passes through a string, this way you can print out variables that holds integers

**Comment by RezSat** [comment]
Try the new release Y# Version 1.0.1, it's all fixed there
